version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install NPM dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/project/node_modules
            - ~/.cache/yarn
      - run:
          name: lint scss
          command: yarn stylelint